spring.config.import=optional:file:.env[.properties]

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=create

spring.security.oauth2.client.registration.github.client-name=Github
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=login

# OAUTH CLIENTS CONFIGURATION, SET THIS IN YOUR ENVIRONMENT VARIABLES
# spring.security.oauth2.client.registration.github.client-id={YOUR_ID_HERE}
# spring.security.oauth2.client.registration.github.client-secret={YOUR_SECRET_HERE}